### PR TITLE
Barcode functionality

### PR DESCRIPTION
**Pull request by long1EU**
This is the right pull request sorry for the last one. :D Thanks again for you work.

### CODE REVIEW

**Comment by long1EU** [comment]
It needs some polish, I did know how to actually fit it in to match your workflow. Please tell me if you need something done. :D

**Comment by long1EU** [comment]
I know, I did it last night in a rush. If you need help let me know.

**Comment by 1gravity** [comment]
I created a new branch "barcode" and did all the wiring so it really works.
There's still some stuff to do like:

- editing an existing barcode at the moment inserts a new one
- removing an existing barcode from the dialog doesn't work either
- the icon needs proper theming so it fits the style of the other icons
- there's a mysterious crash related to removing the fragment, haven't gotten to the bottom of this yet, it happens on an irregular basis when the dialog fragment closes

I would appreciate if you could work on this too. Thank you for your contribution.

**Comment by long1EU** [comment]
Ok, I'm on that. I will get back with you on wednesday.

**Pull request merged**
