### PR TITLE
Changed both spans size calculation from line height to text size. 

### PR DESCRIPTION
**Pull request by lironmosh**
This fix a problem of large spans when added to an image span.

### CODE REVIEW

**Comment by lironmosh** [comment]
Please check again. Before, adding a bullet or number span to an added image using the library causes the bullet / number span size to adjusted to the image size, which is wrong. An example is added.

screen shot 2017-11-06 at 5 15 48 pm 1

**Comment by 1gravity** [comment]
This is intended behavior. If the size of the text changes so does the size of the bullet point / numbering

**Comment by dmapr** [comment]
@1gravity I think that https://github.com/1gravity/Android-RTEditor/pull/119 should address both your and @lironmosh concerns about the sizing

**Comment by 1gravity** [comment]
Resolved by #119

**Pull request closed without merging**
