### PR TITLE
BUG-FIX: Link click combined with right or center alignment didn't work

### PR DESCRIPTION
**Pull request by thelong1EU**
I found the problem. I was looking for this from last year. And here it is.

### CODE REVIEW

**Comment by 1gravity** [comment]
I haven't tested it but I'm fairly certain this won't work for older Android versions. There's a reason I spent all that time calculating the position manually.

**Comment by 1gravity** [comment]
I might have time to look into to on the weekend

**Comment by thelong1EU** [comment]
Ok

**Comment by 1gravity** [comment]
I see two solutions:
- use different code path for different Android versions (older versions would use my code, newer versions would use your code)
- copy the code from TextView.getOffsetForPosition() (Android source code) into the class itself

**Comment by thelong1EU** [comment]
I'll do that tonight.

**Pull request closed without merging**
