### PR TITLE
MOD 1) remove unnecessary String object allocation in RLayout constru…

### PR DESCRIPTION
**Pull request by diegomontoya**
…ctor. substring() returns a String that shares char[] with original string but still needs to allocate a String object regardless. 2) fix wrong usage of String builder in toString() not using append 3) add finals when applicable

### CODE REVIEW

**Comment by 1gravity** [comment]
Thank you for your pull request. I did a commit myself (9bd1262705b196cb41f888a85abb70492ceefece) that reflects your pull request except the toString method. I prefer the for loop because it's easier to read and makes for easier to maintain code.
The final and the StringBuilder optimizations make a lot of sense though.

**Comment by diegomontoya** [comment]
The for loop change was not for aesthetics. In android, a manual for loop when the looped data is an ArrayList is 3 times faster than a iterator() loop.

**Comment by 1gravity** [comment]
The toString method is never called except when debugging the code so there's really no need to optimize this for speed

**Comment by diegomontoya** [comment]
There are lots of other places in the code where the cleaner looking for(T : list<T>) is used but the list is actually a ArrayList(). For those, manual loop could be used for a small boost on android. There are lots of tight loops where this happens. The boot is small but significant when the editor contains tons of paragraphs and/or effects.

**Comment by 1gravity** [comment]
I agree. See: ec0e5360438fa06a6e64809123350f4c3e6c421b.

**Pull request closed without merging**
