### PR TITLE
fixed issue#46. bullet/number is shown when selected and when jumped …

### PR DESCRIPTION
**Pull request by kim1059**
Problem solved:
When bullet/number span is selected and text is empty, the number/bullet is actually shown
When bullet/number span is selected and user goes to new line, the number/bullet is actually shown

### CODE REVIEW

**Comment by kim1059** [comment]
any news on this PR?

**Comment by 1gravity** [comment]
I tested it but still no bullet points or numbering on empty lines

**Comment by kim1059** [comment]
Could you please test again? I have checked on multiple devices and it is working fine. here is demo video https://www.dropbox.com/s/us1qy3e4dq2rd9t/rteditor.mp4?dl=0

**Comment by kim1059** [comment]
any updates on this? :smile:

**Comment by 1gravity** [comment]
There's an issue with this. If you press enter at the start of a line it inserts a new line above the current line instead of at the end, so

1. abc
2. xyz

becomes

1. abc

2. xyz

if the cursor was in front of the x

**Pull request merged**
